Session/5
morikann/flutter_training pull request #18
Opened 2023-04-04 04:49 UTC by morikann

## 課題

close #6 

## 対応箇所

- [ ] xxx

## 動作

| expected | actual |
|----------|--------|
| xxx      | xxx    |

2023-04-04 05:05 UTC, morikann commented on lib/common/result.dart
> +class Result<T, E> with _$Result<T, E> {
Result (union type) を定義してAPIの結果をsuccess, failureで判別できるようにしました。🙋‍♂️

2023-04-04 05:06 UTC, morikann commented
@blendthink 
お手隙の際にレビューよろしくお願いします！🙇‍♂️

2023-04-04 07:19 UTC, blendthink commented
@morikann 
Session4 の内容が入っていないので、main ブランチを取り込んで念の為最新化お願いします！

2023-04-04 08:48 UTC, blendthink requested changes
@morikann 
いくつかコメントしましたので、ご確認お願いします！

2023-04-04 08:48 UTC, blendthink commented on lib/model/weather.dart
> +          return const Result.failure('予期せぬ不具合が発生しました。');
[感想]
エラーの内容によって、メッセージを分けていてとてもステキです✨

2023-04-04 08:48 UTC, blendthink commented on pubspec.yaml
> +  freezed: ^2.3.2
[感想]
`build_runner` は独立したパッケージであるため、コミットを分けるのは自然ですが、 `freezed_annotation` , `freezed` は密接に関わっているパッケージであるため、コミットは一緒にしてしまったほうが、リベースなどもしやすくメリットが大きそうです。

2023-04-04 08:48 UTC, blendthink commented on lib/view/weather_view/component/error_dialog.dart
> +class ErrorDialog extends StatelessWidget {
[感想]
このように Widget を分けていてステキです✨
とても可読性・保守性高い状態で開発進められそうです！

2023-04-04 08:48 UTC, blendthink commented on lib/view/weather_view/weather_page.dart
> +                                  );
[imo]
若干、ネストが深い気がするので、クリックイベントを抽出して　`_WeatherPageState`　のインスタンスメソッドとしてプライベートで定義しておくと、より可読性・保守性が高まりそうで良いかもしれません。

2023-04-04 08:48 UTC, blendthink commented on lib/model/weather.dart
>      } on Exception catch (e) {
[nits]
今気づいたのですが、 `WeatherCondition.values.byName(condition)` でスローされるのは、 `ArgumentError` で `Exception` ではなく `Error` ですので、キャッチすることができていませんでした。。

ただ、 アプリケーションコードで `Error` をキャッチするのはあまりよくないため、 `Exception` をスローするように `WeatherCondition.values.byName(condition);` の拡張関数を自作すると良さそうです！

もし、いまいち分からない場合は、Slack のハドルとかでペアプロできればと思います！

2023-04-05 09:44 UTC, morikann commented on pubspec.yaml
> +  freezed: ^2.3.2
確かにそうですね、ご教示ありがとうございます！
`git rebase -i, squash` を用いて一つのコミットにまとめました！
41b5560bfec4bc62afe29f9749f9a969fa843f34

2023-04-05 09:50 UTC, morikann commented on lib/view/weather_view/weather_page.dart
> +                                  );
ご指摘ありがとうございます！
クリックイベントを`_fetchWeather`メソッドに抽出しました！
また、`_fetchWeather`メソッドのコードが若干長くなった気がしたので、エラー処理を`_showErrorDialog`メソッドに分割しました！
84adc6a9baaaecbcab4512f008c7728947c1586f

2023-04-05 10:02 UTC, morikann commented on lib/model/weather.dart
>      } on Exception catch (e) {
ご指摘ありがとうございます & 本日はハドルにてこの箇所についてご教示いただきありがとうございました🙇‍♂️
命名について悩んでいまして、以下のように修正したのですが問題ないでしょうか？
- `WeatherCondition`の拡張関数を定義することを明確にするために命名を`_WeatherConditionExt`に変更
- `byName`についてはそのままなのですが、他に良い命名があったらご教示いただきたいです🙇‍♂️

1bc880dbba93620cf20924af9cc263a8f52153d6

2023-04-05 10:04 UTC, morikann commented
@blendthink 
Session4 の内容の取り込み & FB修正が完了しましたのでお手隙の際にご確認お願いします！🙇‍♂️

2023-04-05 10:06 UTC, blendthink commented on lib/model/weather.dart
>      } on Exception catch (e) {
@morikann 
あれ、ハドルでお話したときは、命名で悩んだので `byNameOrNull` にして例外をスローしない形にするということになったような気がしていましたが、どうでしたっけ？

2023-04-05 10:29 UTC, morikann commented on lib/model/weather.dart
>      } on Exception catch (e) {
@blendthink 
命名を`byNameOrNull`にするというのを認識できていなかったです...申し訳ございません🙇‍♂️
こちらで例外をスローしない形に修正しました！
44791df8748ecc07ff66dea847e2aef2b923cbe8

お手隙の際にご確認お願いします🙇‍♂️

2023-04-05 10:38 UTC, blendthink commented on lib/model/weather.dart
>      } on Exception catch (e) {
いえいえ、自分の勘違いかもしれないです 🙇 
ご対応ありがとうございます！

2023-04-05 10:41 UTC, blendthink reviewed
@morikann 
１点コメントしましたので、ご確認お願いいたします！

2023-04-05 10:41 UTC, blendthink commented on lib/model/weather.dart
> +      final weatherCondition = WeatherCondition.values.byNameOrNull(condition);
[nits]
`weatherCondition` が `null` になってしまうときは失敗かなと思うので、 `if` で分岐して `null` の場合は、 `const Result.failure('{適切な文言}');` をリターンしていただければいいかなと思います！

2023-04-05 11:33 UTC, morikann commented on lib/model/weather.dart
> +      final weatherCondition = WeatherCondition.values.byNameOrNull(condition);
なるほど、ご指摘ありがとうございます！
確かに`weatherCondition`が`null`の時に`success`として処理するのは違和感がありますね。
こちらで修正しました。！
8e54a5f21e4a746b096d552166c562158768df51

2023-04-05 11:36 UTC, blendthink approved these changes
ご対応ありがとうございます！

![LGTM](https://image.lgtmoon.dev/204104)

2023-04-05 11:37 UTC, morikann commented
レビューありがとうございました！
マージします！

2023-04-05 11:37 UTC, merged